services:
    EzSystems\EzPlatformEnterpriseEditionInstallerBundle\Installer\Installer:
        parent: EzSystems\PlatformInstallerBundle\Installer\CoreInstaller
        tags:
            - {name: ezplatform.installer, type: ezplatform-ee-clean}

    EzSystems\EzPlatformEnterpriseEditionInstallerBundle\Event\Subscriber\BuildSchemaSubscriber:
        autoconfigure: true
        public: false
        arguments:
            - '@=service("kernel").locateResource("@EzPlatformEnterpriseEditionInstallerBundle/Resources/config/storage/schema.yaml")'
